### ISSUE TITLE
NSA

### ISSUE THREAD

**Issue by achetoui-el-mehdi** [achetoui-el-mehdi/security#1]
when we read the PNAC ( protect of the new america century) we conclude the four missions to control all the world by america:
homeland defense, large wars , constabulary duties and transform the US army
let take NSA for example , they work hard every day why ? to break algorithm
maybe , but not their own algorithm , we see that all the cryptography algorithms are invented and developed in america ( by an american or jewish mathematician) , so have you see a person who make a padlock without the key , have you see a person who close the door without think if it can go out after ??? of course no
NSA will never share the key to break their algorithms but they will make it very stronger by showing a big mathemtic equation and big bit sequence ( 2048.....) and also to invent some stories about the inventer and some hackers who broke some algorithms until you beleive that there is no stronger algorithm else what NSA suggest
this is the first step , so all communication with american algorithms are crypted for us but in clear for them
NSA now ,are working on spying on people conversation to gather the maximum of data and information , then analyze it to find who threaten them , and also work to break the new algorithm invented and developed by others to secure thier data and conversation , like the russian army .

**Comment by Atavic** [comment]
Surely some cryptographers have implemented backdoors in their works at some point. When commercial firmware or software use cyrptology techniques it's _100% backdoored_ to satisfy the will of the Agencies. The 'Patriot Act' is another step, as NSA wants to login and tamper thru backdoors freely, without bothering to ask any Corporation, Judge or Politician.

See: http://www.philzimmermann.com/EN/faq/index.html
